### ISSUE TITLE
FindMergeCommits takes a huge amount of time

### ISSUE THREAD

**Issue by benedikt-schesch** [benedikt-schesch/AST-Merging-Evaluation#104]
Currently, on the run-cf branch the script src/main/java/astmergeevaluation/FindMergeCommits.java takes a huge amount of time. It has been running for more than 12h and still has not finished. Three questions:
1) Is there a way to make it work more efficiently for one repo?
2) Is there a way to parallelize the code when we have multiple repos?
3) Is there a way to have some progress bar or progress report, so we can have some ETA estimate?

**Comment by mernst** [comment]
Good ideas.

1. I'm going to hold off on this.
2. #106
3. #105
