### ISSUE TITLE
FindMergeCommits fills up /tmp

### ISSUE THREAD

**Issue by benedikt-schesch** [benedikt-schesch/AST-Merging-Evaluation#114]
/tmp is full again :(. The script crashed due to no storage space remaining. The script leaves many files in scheschb/ast-merge-eval-data/
```
[scheschb@tricycle tmp]$ find scheschb/ast-merge-eval-data/ -user scheschb | wc -l
281415
```

**Comment by benedikt-schesch** [comment]
@mernst Could you maybe look into this? It's not an urgent problem but I think we should fix this.

**Comment by mernst** [comment]
This is handled in https://github.com/benedikt-schesch/AST-Merging-Evaluation/pull/179, whose `make small-test` is failing in Python for reasons I don't understand.

**Comment by mernst** [comment]
Well, partially handled.  It puts files in /scratch which has lots more space, but it does not yet delete them.

**Comment by benedikt-schesch** [comment]
Ok, thank you

**Comment by benedikt-schesch** [comment]
I'll mark it as fixed for now.
