### ISSUE TITLE
Nondeterministic output in `make small-test`

### ISSUE THREAD

**Issue by mernst** [benedikt-schesch/AST-Merging-Evaluation#183]
The `valid_repos.csv` and `local_repos.csv` files should be sorted, for determinism.
Or maybe they should only be sorted in the context of the `make small-test` test.

**Comment by benedikt-schesch** [comment]
I can sort them, but the output should currently be fully deterministic at the moment. Ordering is maintained at all times, even though it is shuffled (deterministically) in `local_repos.csv`.

**Comment by mernst** [comment]
When I add a project, the order changes and so I have to run `make small-test` twice before it will pass locally.
