### ISSUE TITLE
Run time difference in `make small-test`

### ISSUE THREAD

**Issue by mernst** [benedikt-schesch/AST-Merging-Evaluation#222]
I ran
  make small-test
and got the error
  ValueError: test/small-goal-files/result.csv and results-small/result.csv are not equal

The problem was a difference in the run time.  Is such a failure desirable?

**Comment by benedikt-schesch** [comment]
Such failure shouldn't be happening because the script that compares columns does not consider any column containing the word `run_time`. I can't reproduce this problem, and on the CI/CD pipeline it seems to work. Do you maybe have more details?
