### ISSUE TITLE
`FindMergeCommits` Performance

### ISSUE THREAD

**Issue by benedikt-schesch** [benedikt-schesch/AST-Merging-Evaluation#229]
It seems like `FindMergeCommits` struggles with certain repos to list all possible merges. It might not be useful to sample more than 10k+ merges either way, but it would be great for the script to terminate on its own or to be fast enough to process everything.
To reproduce, checkout the branch `merge_analyzer` and run: `sh run_xp.sh` which gets stuck on FindMergeCommits because the repo enonic/xp contains too many merges.

**Comment by mernst** [comment]
@benedikt-schesch I don't see the `run_xp.sh` script either in the main branch or in the xp-performance branch.  Could you double-check that it is committed and pushed?

**Comment by benedikt-schesch** [comment]
My bad, you can find everything on the `merge_analyzer` branch.
