### ISSUE TITLE
Paths for scripts

### ISSUE THREAD

**Issue by mernst** [benedikt-schesch/AST-Merging-Evaluation#359]
The README at https://github.com/plume-lib/merging says:

> Put directory .../merging/src/main/sh/ on your PATH, adjusting "..." according to where you cloned this repository. (Or, use the absolute pathname in uses of *.sh files below.)

The experimental infrastructure does not seem to do this.  At least, what I observed is that it picks up the scripts from my own PATH rather than from the submodule.  This leads to different results when I run it compared to when CI runs it.

**Comment by benedikt-schesch** [comment]
@mernst has this been fixed in one of the PRs?
