### ISSUE TITLE
Return values

### ISSUE THREAD

**Issue by mernst** [benedikt-schesch/AST-Merging-Evaluation#82]
Why do `repo_test` and `head_passes_test` return a string rather than a boolean?
Also, the possible string values that these routines return is not documented.

**Comment by benedikt-schesch** [comment]
This change has recently occurred to improve readability of the code. We would often handle strange values like 0,1,124,126 which didn't have a strong meaning. I would often forget what they mean exactly. It makes it simpler to look at the code with a more expressive return code. Docs are now updated to reflect those changes.
